# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default

steps:
- script: echo First Azur Pipeline!
  displayName: 'Run a one-line script'

- script: mvn clean install
  displayName: 'Building with maven'

- script: java -jar target/JenkinsMaven-1.0-SNAPSHOT.jar
  displayName: 'Runs the Maven Application'